apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktor-jenkins
  namespace: default
spec:
  selector:
    matchLabels:
      app: ktor-jenkins
  template:
    metadata:
      labels:
        app: ktor-jenkins
    spec:
      containers:
      - name: ktor-jenkins
        image: zhanghu0218/ktor-jenkins:<BUILD_TAG>
#         image: harbor.od.com/infra/jenkins:v1.0
#         image: nexus.mimikko.cn:8482/@project.artifactId@:@project.version@.{{ TAG }}
        imagePullPolicy: IfNotPresent
        ports:
            - name: http-port
              containerPort: 8080
        env:
        - name: branch
          value: <BRANCH_NAME>
