apiVersion: apps/v1
kind: Deployment
metadata:
  name: ktor-jenkins
  namespace: default
spec:
  selector:
    matchLabels:
      app: ktor-jenkins
  template:
    metadata:
      labels:
        app: ktor-jenkins
    spec:
      containers:
      - image: zhanghu0218/ktor-jenkins:<BUILD_TAG>
        imagePullPolicy: IfNotPresent
        name: ktor-jenkins
        env:
        - name: branch
          value: <BRANCH_NAME>
